[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"


[dependencies]
yew = "0.19.3"
wasm-bindgen = "0.2.83"
weblog = "0.3.0"
gloo-net = "0.2.4"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen-futures = "0.4"

